CREATE SEQUENCE SEQ_TB_PRODUCT
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE SEQ_TB_RAW_MATERIAL
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE SEQ_TB_PRODUCT_RAW_MATERIAL
    START WITH 1
    INCREMENT BY 1
    NOCACHE;
