CREATE OR REPLACE TRIGGER TRG_TB_PRODUCT_ID
BEFORE INSERT ON TB_PRODUCT
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
    SELECT SEQ_TB_PRODUCT.NEXTVAL
    INTO :NEW.ID
    FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_TB_RAW_MATERIAL_ID
BEFORE INSERT ON TB_RAW_MATERIAL
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
    SELECT SEQ_TB_RAW_MATERIAL.NEXTVAL
    INTO :NEW.ID
    FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_TB_PRODUCT_RAW_MATERIAL_ID
BEFORE INSERT ON TB_PRODUCT_RAW_MATERIALS
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
    SELECT SEQ_TB_PRODUCT_RAW_MATERIAL.NEXTVAL
    INTO :NEW.ID
    FROM DUAL;
END;
/
